name: .NET Core

on: 
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release "./src/ImageWizard.Core"
    - name: Run unit tests
      run: dotnet test "./src/ImageWizard.Core"
    - name: Create the package
      run: dotnet pack --configuration Release "./src/ImageWizard.Core"
    - name: Publish to github packages
      run: dotnet nuget push "./src/ImageWizard.Core/bin/Release/*.nupkg" --source "github"