name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/usercode/index.json
      env:
       NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}  
    - name: Build with dotnet
      run: dotnet build --configuration Release "src\ImageWizard.Core"
    - name: Create the package
      run: dotnet pack --configuration Release "src\ImageWizard.Core"
    - name: Publish the package to GPR
      run: dotnet nuget push "src\ImageWizard.Core\bin\Release\*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "test"
